### ISSUE TITLE
求指教这个问题怎么导致的呢

### ISSUE THREAD

**Issue by wanghao19970205** [PaddlePaddle/InterpretDL#3]
你好，同是厂内开发人员，尝试用这个工具，跑了代码库里的InterpretDL/tutorials/normlime_tutorial_nlp.ipynb
，模型数据都下好了，跑的时候报错，不知道具体是什么意思，求指教
total of 1200 sentences
  0%|          | 0/1200 [00:00<?, ?it/s]2020-12-18 11:44:57,011-WARNING: /Users/wanghao81/senta_model/bilstm_model/params/checkpoint.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-12-18 11:44:57,211-WARNING: /Users/wanghao81/senta_model/bilstm_model/params.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-12-18 11:44:57,211-WARNING: variable file [ /Users/wanghao81/senta_model/bilstm_model/params/learning_rate_0 /Users/wanghao81/senta_model/bilstm_model/params/lstm_0.b_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_2.b_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_0.b_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/embedding_0.w_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/lstm_1.w_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_0.w_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_3.w_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_1.b_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_1.w_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_3.b_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/lstm_1.b_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/fc_2.w_0_moment_0 /Users/wanghao81/senta_model/bilstm_model/params/lstm_0.w_0_moment_0 ] not used
Load model from /Users/wanghao81/senta_model/bilstm_model/params
  4%|▍         | 52/1200 [00:03<01:09, 16.61it/s]
Traceback (most recent call last):
  File "/Users/wanghao81/InterpretDL/tutorials/test.py", line 67, in <module>
    batch_size=10)
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/_normlime_base.py", line 400, in interpret
    auto_save=(i % 10) == 0)
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/_normlime_base.py", line 271, in _get_lime_weights
    batch_size=batch_size)
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/lime.py", line 342, in interpret
    probability = self.predict_fn(*self.model_inputs)[0]
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/lime.py", line 417, in predict_fn
    for i, d in enumerate(params)})
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&&&, char const*, int)
1   void paddle::operators::math::CopyValidData<float>(paddle::framework::Tensor*, paddle::framework::Tensor const*, paddle::framework::CPUVector<unsigned long> const&, int, int, bool, paddle::operators::math::CopyType, paddle::operators::math::PadLayout)
2   paddle::operators::math::UnpaddingLoDTensorFunctor<paddle::platform::CPUDeviceContext, float>::operator()(paddle::platform::CPUDeviceContext const&, paddle::framework::LoDTensor const&, paddle::framework::LoDTensor*, int, int, bool, paddle::operators::math::PadLayout)
3   paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, float>::Compute(paddle::framework::ExecutionContext const&) const
4   std::__1::__function::__func<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&), std::__1::allocator<paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 0ul, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SequenceUnpadOpKernel<paddle::platform::CPUDeviceContext, long long> >::operator()(char const*, char const*, int) const::'lambda'(paddle::framework::ExecutionContext const&)>, void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&)
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
7   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
8   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long long, long long, bool, bool, bool)
9   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::string, std::__1::allocator<std::string > > const&, bool, bool)
10  void pybind11::cpp_function::initialize<paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_111, void, paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::string, std::__1::allocator<std::string > > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(paddle::pybind::pybind11_init_core_avx(pybind11::module&)::$_111&&, void (*)(paddle::framework::Executor&, paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::__1::vector<std::string, std::__1::allocator<std::string > > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::'lambda'(pybind11::detail::function_call&)::__invoke(pybind11::detail::function_call&)
11  pybind11::cpp_function::dispatcher(_object*, _object*, _object*)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/Users/wanghao81/opt/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/layers/sequence_lod.py", line 1057, in sequence_unpad
    outputs={'Out': out})
  File "/Users/wanghao81/InterpretDL/tutorials/assets/bilstm.py", line 106, in bilstm
    emb = fluid.layers.sequence_unpad(emb, length=seq_len)
  File "/Users/wanghao81/InterpretDL/tutorials/test.py", line 36, in paddle_model
    probs = bilstm(word_ids, seq_len, None, DICT_DIM, is_prediction=True)
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/lime.py", line 392, in _paddle_prepare
    probs = self.paddle_model(*data_ops)
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/lime.py", line 340, in interpret
    self._paddle_prepare()
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/_normlime_base.py", line 271, in _get_lime_weights
    batch_size=batch_size)
  File "/Users/wanghao81/InterpretDL/interpretdl/interpreter/_normlime_base.py", line 400, in interpret
    auto_save=(i % 10) == 0)
  File "/Users/wanghao81/InterpretDL/tutorials/test.py", line 67, in <module>
    batch_size=10)

----------------------
Error Message Summary:
----------------------
Error: The padded sequence length can not be less than its original length.
  [Hint: Expected pad_seq_len >= valid_seq_len, but received pad_seq_len:256 < valid_seq_len:278.] at (/home/teamcity/work/ef54dc8a5b211854/paddle/fluid/operators/math/sequence_padding.cc:38)
  [operator < sequence_unpad > error]

Process finished with exit code 1

**Comment by wanghao19970205** [comment]
我尝试将MAX_SEQ_LEN扩大，但总有比MAX_SEQ_LEN还长的seq，最后还是报这个错

**Comment by XuanyuWu123** [comment]
你好，我们在我们的环境下暂时没有出现这个错误。出错的原因可能是因为fluid.layers.sequence_unpad里的length不能大于原来的sequence length，可以把notebook里的preprocess_fn中的seq_lens = [len(sub_word_ids)]改成seq_lens = [min(len(sub_word_ids), MAX_SEQ_LEN)]再试一下吗？

**Comment by wanghao19970205** [comment]
非常感谢，该问题已经解决！
